### PR TITLE
Add odoo-intellij 

### PR DESCRIPTION
**Pull request by 3mrdev**
Support for developing Odoo applications and modules with IntelliJ IDEA and PyCharm IDEs.

### CODE REVIEW

**Comment by obiefy** [comment]
@3mrdev Can you please remove the badge, and we can keep the plain description.

**Comment by 3mrdev** [comment]
Removed @obiefy

**Comment by obiefy** [comment]
@3mrdev Thanks for this PR :)

**Comment by 3mrdev** [comment]
You are welcome @obiefy thanks for such an idea

**Pull request merged**
